version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.18
    commands:
      - go mod tidy
  build:
    commands:
      - go build -o my-api main.go
      - go test -coverprofile=coverage2.txt -covermode count ./
  post_build:
    commands:
      - zip -r my-api.zip my-api

artifacts:
  files:
    - ./*


